name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: redfyel/contrib-pie-generator/.github/workflows/main.yml@v0
    with:
      chart-size: '7,7'
      repo-url: "https://api.github.com/repos/redfyel/AcademiaConnect/contributors"
